env:
  global:
    - CC_TEST_REPORTER_ID=93d0b0fd6a03db2b1e8a91fae1e83d23fdf4ffb7baabb2a00fc9363e3e62ed36
language: ruby
rvm:
  - 2.4.1
before_install: gem install bundler -v 1.16.1
notifications:
  - false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rake db:create
scripts:
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
